### PR TITLE
Add disk space monitor

### PR DESCRIPTION
**Pull request by lv-zheng**
Add disk space monitor for a filesystem specified in command line
options. The web frontend can be made more good looking.

In this commit, the command line options change. This may break old
scripts.

### CODE REVIEW

**Comment by htfy96** [comment]
Can you also update command-line usage in `README.md`?

**Comment by Endle** [comment]
这个PR和[prepare_watcher](https://github.com/sjtug/mirror-docker/tree/prepare_watcher)冲突吗？
如果冲突，我提议把这个PR先suspend掉

**Comment by htfy96** [comment]
@Endle 不冲突。

**Comment by lv-zheng** [comment]
README updated.
However, the web front-end is still terrible.

**Comment by lv-zheng** [comment]
@htfy96 @Endle added as collaborators to my forked repo.

**Pull request merged**
